- hosts: all
  become: true
  become_user: root
  tasks:
    - name: stop basic service
      service:
         enabled: yes
         name: "{{ item }}"
         state: stopped
      with_items:
        - supervisord

- hosts: etcd
  tasks:
    - name: destroy
      file: 
        path: "{{ item }}"
        state: absent
      with_items: 
        - "{{ etcd_install_path }}"
        - /etc/supervisord.d/etcd.ini

- hosts: master
  tasks:
    - name: destroy
      file: 
        path: "{{ item }}"
        state: absent
      with_items: 
        - "{{ apiserver_install_path }}"
        - "{{ controller_install_path }}"
        - "{{ scheduler_install_path }}"
        - "{{ admin_install_path }}"
        - /etc/supervisord.d/apiserver.ini
        - /etc/supervisord.d/controller.ini
        - /etc/supervisord.d/scheduler.ini

- hosts: master
  tasks:
    - name: destroy
      file: 
        path: "{{ item }}"
        state: absent
      with_items: 
        - "{{ kubelet_install_path }}"
        - "{{ kuberouter_install_path }}"
        - "{{ cni_install_path }}"
        - /etc/supervisord.d/kubelet.ini
        - /etc/supervisord.d/kube-router.ini
