- hosts: all
  become: true
  become_user: root
  tasks:
    - name: start basic service
      service:
        enabled: yes
        name: "{{ item }}"
        state: started
      with_items:
        - supervisord

- hosts: etcd
  roles:
    - etcd
- hosts: master
  roles:
    - apiserver
    - controller
    - scheduler
    - admin
- hosts: node
  roles:
    - docker
    - cni
    - kubelet
    - kube-proxy
#    - kube-router
