- hosts: localhost
  gather_facts: no
  tasks:
    - name: checkout kong code
      git:
          repo: '{{ item.repo }}'
          dest: "{{ kong_proxy_code_path }}/{{ item.dir }}"
          version: '{{ item.version }}'
          force: yes
      with_items:      
        - { repo: "{{ kong_proxy_repo }}" , version: "{{ kong_proxy_version }}", dir: "kong" }

- hosts: localhost
  gather_facts: no
  tasks:
    - name: compress kong code
      shell: |
        cd "{{ kong_proxy_code_path }}"
        tar -czvf "{{ item }}.gz" "{{ item }}"
      with_items:      
        - "kong"

#- hosts: kong-proxy
#  gather_facts: no
#  tasks:
#    - name: mkdir backup
#      file:
#        path: "{{ kong_proxy_backup_path }}"
#        state: directory
#    - name: backup config and binary
#      shell: |
#        if [ -d "{{ kong_proxy_install_path }}" ]; then mv "{{ kong_proxy_install_path }}" "{{ kong_proxy_backup_path }}/kong-backup-{{ DATE }}"; fi

- hosts: kong-proxy
  gather_facts: yes
  roles:
    - kong-proxy
