- name: apiserver certs directory
  tags: cert
  file:
    path: "{{ apiserver_certs_path }}/{{ item }}"
    state: directory
  with_items:      
    - "{{ groups['apiserver'] }}"

- name: apiserver key
  tags: cert
  openssl_privatekey:
    path: "{{ apiserver_certs_path }}/{{ item }}/key.pem"
  with_items:      
    - "{{ groups['apiserver'] }}"

- name: apiserver csr
  tags: cert
  openssl_csr:
    path: "{{ apiserver_certs_path }}/{{ item }}/cert.csr"
    privatekey_path: "{{ apiserver_certs_path }}/{{ item }}/key.pem"
    common_name: "{{ item }}"
  with_items:      
    - "{{ groups['apiserver'] }}"

- name: apiserver req extensions  
  template:
    src: apiserver_extention.conf.j2
    dest: "{{ apiserver_certs_path }}/{{ item }}/extention.conf"
  with_items:      
    - "{{ groups['apiserver'] }}"

# this task will always generate new certs to cover previous certs
- name: apiserver cert
  tags: cert
  shell: if [ -f {{ apiserver_certs_path }}/{{ item }}/cert.pem ];then exit; else openssl x509 -req -days 365 -in {{ apiserver_certs_path }}/{{ item }}/cert.csr -CA {{ ca_path }}/ca.pem  -CAkey {{ ca_path }}/key.pem -CAcreateserial -out {{ apiserver_certs_path }}/{{ item }}/cert.pem  -extensions v3_ca -extfile {{ apiserver_certs_path }}/{{ item }}/extention.conf; fi
  with_items:      
    - "{{ groups['apiserver'] }}"
